"""add contact association tables

Revision ID: 07aa5311b296
Revises: 10b036fe305f
Create Date: 2025-07-17 15:24:23.320976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07aa5311b296'
down_revision: Union[str, Sequence[str], None] = '10b036fe305f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suite_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.suite_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utility_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.utility_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('services_contact_id_fkey'), 'services', type_='foreignkey')
    op.drop_column('services', 'contact_id')
    op.drop_constraint(op.f('suites_contact_id_fkey'), 'suites', type_='foreignkey')
    op.drop_column('suites', 'contact_id')
    op.drop_constraint(op.f('utilities_contact_id_fkey'), 'utilities', type_='foreignkey')
    op.drop_column('utilities', 'contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilities', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('utilities_contact_id_fkey'), 'utilities', 'contacts', ['contact_id'], ['contact_id'])
    op.add_column('suites', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('suites_contact_id_fkey'), 'suites', 'contacts', ['contact_id'], ['contact_id'])
    op.add_column('services', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('services_contact_id_fkey'), 'services', 'contacts', ['contact_id'], ['contact_id'])
    op.drop_table('utility_contacts')
    op.drop_table('suite_contacts')
    op.drop_table('service_contacts')
    # ### end Alembic commands ###
