"""Add contacts table and contact_id foreign keys

Revision ID: 10b036fe305f
Revises: 
Create Date: 2025-07-17 15:07:38.442561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b036fe305f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('office_number', sa.String(), nullable=True),
    sa.Column('cell_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.drop_index(op.f('idx_codes_description'), table_name='codes')
    op.create_index(op.f('ix_codes_description'), 'codes', ['description'], unique=False)
    op.drop_index(op.f('idx_properties_building_type'), table_name='properties')
    op.drop_index(op.f('idx_properties_city'), table_name='properties')
    op.drop_index(op.f('idx_properties_prop_manager'), table_name='properties')
    op.drop_index(op.f('idx_properties_zip'), table_name='properties')
    op.create_index(op.f('ix_properties_building_type'), 'properties', ['building_type'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_prop_manager'), 'properties', ['prop_manager'], unique=False)
    op.create_index(op.f('ix_properties_zip'), 'properties', ['zip'], unique=False)
    op.add_column('services', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_services_vendor'), table_name='services')
    op.create_index(op.f('ix_services_vendor'), 'services', ['vendor'], unique=False)
    op.create_foreign_key(None, 'services', 'contacts', ['contact_id'], ['contact_id'])
    op.drop_column('services', 'phone_number')
    op.drop_column('services', 'email_address')
    op.drop_column('services', 'contact')
    op.add_column('suites', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_suites_name'), table_name='suites')
    op.create_index(op.f('ix_suites_name'), 'suites', ['name'], unique=False)
    op.create_foreign_key(None, 'suites', 'contacts', ['contact_id'], ['contact_id'])
    op.drop_column('suites', 'phone_number')
    op.drop_column('suites', 'email_address')
    op.drop_column('suites', 'contact')
    op.add_column('utilities', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_utilities_vendor'), table_name='utilities')
    op.create_index(op.f('ix_utilities_vendor'), 'utilities', ['vendor'], unique=False)
    op.create_foreign_key(None, 'utilities', 'contacts', ['contact_id'], ['contact_id'])
    op.drop_column('utilities', 'contact_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilities', sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'utilities', type_='foreignkey')
    op.drop_index(op.f('ix_utilities_vendor'), table_name='utilities')
    op.create_index(op.f('idx_utilities_vendor'), 'utilities', ['vendor'], unique=False)
    op.drop_column('utilities', 'contact_id')
    op.add_column('suites', sa.Column('contact', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('suites', sa.Column('email_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('suites', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'suites', type_='foreignkey')
    op.drop_index(op.f('ix_suites_name'), table_name='suites')
    op.create_index(op.f('idx_suites_name'), 'suites', ['name'], unique=False)
    op.drop_column('suites', 'contact_id')
    op.add_column('services', sa.Column('contact', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('email_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_vendor'), table_name='services')
    op.create_index(op.f('idx_services_vendor'), 'services', ['vendor'], unique=False)
    op.drop_column('services', 'contact_id')
    op.drop_index(op.f('ix_properties_zip'), table_name='properties')
    op.drop_index(op.f('ix_properties_prop_manager'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_building_type'), table_name='properties')
    op.create_index(op.f('idx_properties_zip'), 'properties', ['zip'], unique=False)
    op.create_index(op.f('idx_properties_prop_manager'), 'properties', ['prop_manager'], unique=False)
    op.create_index(op.f('idx_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('idx_properties_building_type'), 'properties', ['building_type'], unique=False)
    op.drop_index(op.f('ix_codes_description'), table_name='codes')
    op.create_index(op.f('idx_codes_description'), 'codes', ['description'], unique=False)
    op.drop_table('contacts')
    # ### end Alembic commands ###
