"""add active field to property

Revision ID: 73303c310396
Revises: 07aa5311b296
Create Date: 2025-07-21 14:28:01.419955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73303c310396'
down_revision: Union[str, Sequence[str], None] = '07aa5311b296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.add_column('properties', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('properties', 'misc')
    op.drop_constraint(op.f('service_contacts_service_id_fkey'), 'service_contacts', type_='foreignkey')
    op.drop_constraint(op.f('service_contacts_contact_id_fkey'), 'service_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'service_contacts', 'contacts', ['contact_id'], ['contact_id'])
    op.create_foreign_key(None, 'service_contacts', 'services', ['service_id'], ['service_id'])
    op.drop_constraint(op.f('suite_contacts_contact_id_fkey'), 'suite_contacts', type_='foreignkey')
    op.drop_constraint(op.f('suite_contacts_suite_id_fkey'), 'suite_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'suite_contacts', 'contacts', ['contact_id'], ['contact_id'])
    op.create_foreign_key(None, 'suite_contacts', 'suites', ['suite_id'], ['suite_id'])
    op.drop_constraint(op.f('utility_contacts_contact_id_fkey'), 'utility_contacts', type_='foreignkey')
    op.drop_constraint(op.f('utility_contacts_utility_id_fkey'), 'utility_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'utility_contacts', 'contacts', ['contact_id'], ['contact_id'])
    op.create_foreign_key(None, 'utility_contacts', 'utilities', ['utility_id'], ['utility_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utility_contacts', type_='foreignkey')
    op.drop_constraint(None, 'utility_contacts', type_='foreignkey')
    op.create_foreign_key(op.f('utility_contacts_utility_id_fkey'), 'utility_contacts', 'utilities', ['utility_id'], ['utility_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('utility_contacts_contact_id_fkey'), 'utility_contacts', 'contacts', ['contact_id'], ['contact_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'suite_contacts', type_='foreignkey')
    op.drop_constraint(None, 'suite_contacts', type_='foreignkey')
    op.create_foreign_key(op.f('suite_contacts_suite_id_fkey'), 'suite_contacts', 'suites', ['suite_id'], ['suite_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('suite_contacts_contact_id_fkey'), 'suite_contacts', 'contacts', ['contact_id'], ['contact_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'service_contacts', type_='foreignkey')
    op.drop_constraint(None, 'service_contacts', type_='foreignkey')
    op.create_foreign_key(op.f('service_contacts_contact_id_fkey'), 'service_contacts', 'contacts', ['contact_id'], ['contact_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('service_contacts_service_id_fkey'), 'service_contacts', 'services', ['service_id'], ['service_id'], ondelete='CASCADE')
    op.add_column('properties', sa.Column('misc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'active')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
