"""added indexs to service types

Revision ID: b60a7c672b16
Revises: 56819de1b10d
Create Date: 2025-07-24 11:39:02.246490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60a7c672b16'
down_revision: Union[str, Sequence[str], None] = '56819de1b10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_service_type'), 'services', ['service_type'], unique=False)
    op.create_index(op.f('ix_utilities_service'), 'utilities', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilities_service'), table_name='utilities')
    op.drop_index(op.f('ix_services_service_type'), table_name='services')
    # ### end Alembic commands ###
