"""add permits table

Revision ID: dd4b1891995c
Revises: 00ce60112b7e
Create Date: 2025-12-19 11:37:59.496746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4b1891995c'
down_revision: Union[str, Sequence[str], None] = '00ce60112b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permits',
    sa.Column('permit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_yardi', sa.String(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=True),
    sa.Column('equip', sa.String(), nullable=True),
    sa.Column('permit_number', sa.String(), nullable=True),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('exp_date', sa.String(), nullable=True),
    sa.Column('renewal_info', sa.Text(), nullable=True),
    sa.Column('annual_report', sa.Text(), nullable=True),
    sa.Column('login_creds', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_yardi'], ['properties.yardi'], ),
    sa.PrimaryKeyConstraint('permit_id')
    )
    op.create_index(op.f('ix_permits_equip'), 'permits', ['equip'], unique=False)
    op.create_index(op.f('ix_permits_municipality'), 'permits', ['municipality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permits_municipality'), table_name='permits')
    op.drop_index(op.f('ix_permits_equip'), table_name='permits')
    op.drop_table('permits')
    # ### end Alembic commands ###
