"""added edit history table

Revision ID: fe1a7fe6497d
Revises: b60a7c672b16
Create Date: 2025-07-24 16:47:38.974495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1a7fe6497d'
down_revision: Union[str, Sequence[str], None] = 'b60a7c672b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_history_action'), 'edit_history', ['action'], unique=False)
    op.create_index(op.f('ix_edit_history_edited_by'), 'edit_history', ['edited_by'], unique=False)
    op.create_index(op.f('ix_edit_history_entity_id'), 'edit_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_edit_history_entity_type'), 'edit_history', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edit_history_entity_type'), table_name='edit_history')
    op.drop_index(op.f('ix_edit_history_entity_id'), table_name='edit_history')
    op.drop_index(op.f('ix_edit_history_edited_by'), table_name='edit_history')
    op.drop_index(op.f('ix_edit_history_action'), table_name='edit_history')
    op.drop_table('edit_history')
    # ### end Alembic commands ###
